/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import classes.Client;
import classes.Connexion;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.*;

/**
 *
 * @author SystellCOM
 */
public class GestionClients extends javax.swing.JFrame {

    Statement stm;
    Connexion maconnexion = new Connexion();

    /**
     * Creates new form GestionClients
     */
    public GestionClients() {
        initComponents();
        // afficherClient permet de rafraichir automatiquement le tableau contenant les clients
        afficherClient();
    }

    //Afficher les données de la table
    //On crée une liste de tableau afin de stocker les clients
    public ArrayList<Client> liste_client() {
        ArrayList<Client> liste_client = new ArrayList<>();
        String requeteSelect = "SELECT * FROM client order by id";
        ResultSet rs;
        try {
            stm = maconnexion.ObtenirConnexion().createStatement();
            rs = stm.executeQuery(requeteSelect);
            Client client;
            while (rs.next()) {
                client = new Client(rs.getInt("id"), rs.getString("nom"), rs.getString("prenom"), rs.getString("adresse"), rs.getString("email"), rs.getString("telephone"), rs.getString("ville"), rs.getString("fonction"));
                liste_client.add(client);
            }

        } catch (SQLException ex) {
            System.out.println(ex);
        }
        return liste_client;
    }

    //Afficher les données à l'ajout
    public void afficherClient() {
        ArrayList<Client> liste = liste_client();
        DefaultTableModel model = (DefaultTableModel) table_clients.getModel();
        model.setRowCount(0);
        Object[] row = new Object[8];
        for (int i = 0; i < liste.size(); i++) {
            row[0] = liste.get(i).getId();
            row[1] = liste.get(i).getNom();
            row[2] = liste.get(i).getPrenom();
            row[3] = liste.get(i).getAdresse();
            row[4] = liste.get(i).getEmail();
            row[5] = liste.get(i).getTelephone();
            row[6] = liste.get(i).getVille();
            row[7] = liste.get(i).getFonction();
            model.addRow(row);
        }

    }

    //Vider les champs
    //Une methode qui permet de vider les champs et mettre les valeurs par défaut
    public void viderChamps() {
        txt_nom.setText("");
        txt_prenom.setText("");
        txt_adresse.setText("");
        txt_email.setText("");
        txt_telephone.setText("");
        cb_ville.setSelectedItem("Brazzaville");
        txt_fonction.setText("");
    }

    //Afficher les valeurs du tableau dans les champs
    //La méthode fichierVersEcran servira d'afficher les informations pour le boutton afficher
    public void fichierVersEcran() {
        //Afficher les informations sur le champ
        //Faire référence à la ligne selectionnée
        int index = table_clients.getSelectedRow();
        //Définir les valeurs du tableau comme valeurs des champs de saisie
        txt_nom.setText(liste_client().get(index).getNom());
        txt_prenom.setText(liste_client().get(index).getPrenom());
        txt_adresse.setText(liste_client().get(index).getAdresse());
        txt_email.setText(liste_client().get(index).getEmail());
        txt_telephone.setText(liste_client().get(index).getTelephone());
        cb_ville.setSelectedItem(liste_client().get(index).getVille());
        txt_fonction.setText(liste_client().get(index).getFonction());
    }

    //Methode permettant de rechercher un client
    public void rechercher(String str) {
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) table_clients.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        table_clients.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        txt_adresse = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_prenom = new javax.swing.JTextField();
        txt_telephone = new javax.swing.JTextField();
        txt_fonction = new javax.swing.JTextField();
        cb_ville = new javax.swing.JComboBox<>();
        btn_rechercher = new javax.swing.JButton();
        btn_ajouter = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        btn_afficher = new javax.swing.JButton();
        btn_annuler = new javax.swing.JButton();
        btn_retour_dashboard = new javax.swing.JButton();
        txt_rechercher = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_clients = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1130, 562));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Open Sans Light", 1, 18)); // NOI18N
        jLabel1.setText("ENREGISTREMENT DES CLIENTS");

        jPanel2.setBackground(new java.awt.Color(246, 246, 246));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(246, 246, 246), 1, true));

        jLabel2.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("NOM : ");

        jLabel3.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PRENOM : ");

        jLabel4.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ADRESSE : ");

        jLabel5.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EMAIL : ");

        jLabel6.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TELEPHONE : ");

        jLabel7.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("VILLE : ");

        jLabel8.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FONCTION : ");

        cb_ville.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brazzaville", "Pointe-Noire", "Bouenza", "Cuvette", "Cuvette-Ouest", "Lékoumou", "Likouala", "Niari", "Plateaux", "Pool", "Sangha", "Kouilou" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_email)
                    .addComponent(txt_nom)
                    .addComponent(txt_prenom)
                    .addComponent(txt_adresse)
                    .addComponent(txt_telephone)
                    .addComponent(cb_ville, 0, 244, Short.MAX_VALUE)
                    .addComponent(txt_fonction))
                .addGap(107, 107, 107))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cb_ville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txt_fonction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        btn_rechercher.setBackground(new java.awt.Color(0, 128, 255));
        btn_rechercher.setFont(new java.awt.Font("Open Sans SemiBold", 1, 14)); // NOI18N
        btn_rechercher.setForeground(new java.awt.Color(255, 255, 255));
        btn_rechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_search_more_25px.png"))); // NOI18N
        btn_rechercher.setText("Recherche");
        btn_rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rechercherActionPerformed(evt);
            }
        });

        btn_ajouter.setBackground(new java.awt.Color(0, 156, 19));
        btn_ajouter.setFont(new java.awt.Font("Open Sans SemiBold", 1, 12)); // NOI18N
        btn_ajouter.setForeground(new java.awt.Color(255, 255, 255));
        btn_ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Plus_25px_2.png"))); // NOI18N
        btn_ajouter.setText("Ajouter");
        btn_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouterActionPerformed(evt);
            }
        });

        btn_modifier.setBackground(new java.awt.Color(0, 156, 19));
        btn_modifier.setFont(new java.awt.Font("Open Sans SemiBold", 1, 12)); // NOI18N
        btn_modifier.setForeground(new java.awt.Color(255, 255, 255));
        btn_modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_edit_25px.png"))); // NOI18N
        btn_modifier.setText("Modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });

        btn_supprimer.setBackground(new java.awt.Color(255, 102, 102));
        btn_supprimer.setFont(new java.awt.Font("Open Sans SemiBold", 1, 12)); // NOI18N
        btn_supprimer.setForeground(new java.awt.Color(255, 255, 255));
        btn_supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_remove_25px.png"))); // NOI18N
        btn_supprimer.setText("Supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        btn_afficher.setFont(new java.awt.Font("Open Sans SemiBold", 1, 12)); // NOI18N
        btn_afficher.setForeground(new java.awt.Color(255, 255, 255));
        btn_afficher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_eye_25px.png"))); // NOI18N
        btn_afficher.setText("Afficher");
        btn_afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_afficherActionPerformed(evt);
            }
        });

        btn_annuler.setBackground(java.awt.SystemColor.textHighlight);
        btn_annuler.setFont(new java.awt.Font("Open Sans SemiBold", 1, 12)); // NOI18N
        btn_annuler.setForeground(new java.awt.Color(0, 128, 255));
        btn_annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_reset_25px.png"))); // NOI18N
        btn_annuler.setText("Annuler");
        btn_annuler.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 128, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 128, 255), null));
        btn_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annulerActionPerformed(evt);
            }
        });

        btn_retour_dashboard.setFont(new java.awt.Font("Open Sans SemiBold", 1, 12)); // NOI18N
        btn_retour_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_go_back_25px_1.png"))); // NOI18N
        btn_retour_dashboard.setText("Retour");
        btn_retour_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retour_dashboardActionPerformed(evt);
            }
        });

        txt_rechercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_rechercherKeyReleased(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        table_clients.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        table_clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOM", "PRENOM", "ADRESSE", "EMAIL", "TELEPHONE", "VILLE", "FONCTION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_clients.setRowHeight(20);
        jScrollPane1.setViewportView(table_clients);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btn_rechercher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_ajouter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_afficher, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_annuler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_modifier, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_retour_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(70, 70, 70))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_rechercher))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_supprimer)
                            .addComponent(btn_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ajouter))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_afficher)
                            .addComponent(btn_retour_dashboard)
                            .addComponent(btn_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouterActionPerformed
        // Bouton permettant d'ajouter des clients
        
        //On déclare les variables qui auront comme valeur le texte situé dans le champ de texte
        String nom = txt_nom.getText(), prenom = txt_prenom.getText(),
                adresse = txt_adresse.getText(), email = txt_email.getText(),
                telephone = txt_telephone.getText(), fonction = txt_fonction.getText();
        String ville = (String) cb_ville.getSelectedItem();

        //On défini la requete sql d'insertion
        String requete_ajout = "INSERT INTO client (nom, prenom, adresse, email, telephone, ville, fonction)"
                + "VALUES('" + nom + "','" + prenom + "','" + adresse + "','" + email + "','" + telephone + "','" + ville + "','" + fonction + "')";

        try {
            
            //Si les champs sont vides, on ne peut pas inserer des données
            if (nom.equals("")
                    || prenom.equals("")
                    || adresse.equals("")
                    || email.equals("")
                    || telephone.equals("")
                    || fonction.equals("")) {
                //On affiche alors un message
                JOptionPane.showMessageDialog(null, "Veuillez entrer tous les champs s'il vous plaît");
            } else {
                
                //sinon on insert les données
                stm = maconnexion.ObtenirConnexion().createStatement();
                stm.executeUpdate(requete_ajout);
                
                //On met à jour automatiquement le tableau contenant les clients
                afficherClient();
                
                //On affiche un message disant que le client a bien été ajouté
                JOptionPane.showMessageDialog(null, "Client ajouté avec succès");
                //On vide les champs de saisie
                viderChamps();
            }

        } catch (SQLException ex) {
            System.err.println(ex);
        }

    }//GEN-LAST:event_btn_ajouterActionPerformed

    private void btn_retour_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retour_dashboardActionPerformed
       //Bouton permettant de revenir vers le tableau de bord
        new GestionTableauxBord().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_retour_dashboardActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        // Bouton permettant de suppimer un client selectionné dans le tableau
        
        // On 
        int index = table_clients.getSelectedRow();
        try {
            if (JOptionPane.showConfirmDialog(null, "attention vous avez supprimer un client etes-vous sûr?", "Suppimer client",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                if (true) {

                    stm.executeUpdate("DELETE from client where id= '" + liste_client().get(index).getId() + "'   ");
                    afficherClient();
                    viderChamps();
                    JOptionPane.showMessageDialog(null, "Client suppimé");
                    // afficherClient();
                } else {
                    JOptionPane.showMessageDialog(null, "veuillez remplir le champs id");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erreur de supprimer /n" + e.getMessage());
            System.err.println(e);
        }
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void btn_afficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_afficherActionPerformed
        fichierVersEcran();
        if (!txt_nom.getText().equals("")
                || !txt_prenom.getText().equals("")
                || !txt_adresse.getText().equals("")
                || !txt_email.getText().equals("")
                || !txt_telephone.getText().equals("")
                || !txt_fonction.getText().equals("")) {
            btn_ajouter.setEnabled(false);
        }
        


    }//GEN-LAST:event_btn_afficherActionPerformed

    private void btn_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_annulerActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Voulez-vous annuler et vider les champs?", "Annuler et vider les champs",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
            if (true) {
                viderChamps();
                btn_ajouter.setEnabled(true);
            }

        }
    }//GEN-LAST:event_btn_annulerActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
        // TODO add your handling code here:
        //Modifier les informations afficher

        int index = table_clients.getSelectedRow();
        try {
            if (txt_nom.getText().equals("")
                    || txt_prenom.getText().equals("")
                    || txt_adresse.getText().equals("")
                    || txt_email.getText().equals("")
                    || txt_telephone.getText().equals("")
                    || txt_fonction.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Aucun client n'a été affiché pour procéder à la modifiaction");
            } else {
                btn_ajouter.setEnabled(false);
                if (JOptionPane.showConfirmDialog(null, "Confirmer la modification", "Modification",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                    stm.executeUpdate("UPDATE client SET nom='" + txt_nom.getText() + "',prenom='" + txt_prenom.getText()
                            + "',adresse='" + txt_adresse.getText() + "',email='"
                            + txt_email.getText() + "',telephone='" + txt_telephone.getText()
                            + "',ville='" + cb_ville.getSelectedItem() + "',fonction='" + txt_fonction.getText()
                            + "'where id= '" + liste_client().get(index).getId() + "'   ");
                    afficherClient();
                    viderChamps();
                    btn_ajouter.setEnabled(true);
                    JOptionPane.showMessageDialog(null, "Modification effectuée avec succès");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "erreur de modification!!!!!");
            System.err.println(e);
        }
    }//GEN-LAST:event_btn_modifierActionPerformed

    private void btn_rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rechercherActionPerformed
        // TODO add your handling code here:
        //Rechercher par nom
        String zone_recherche = txt_rechercher.getText();
        rechercher(zone_recherche);
    }//GEN-LAST:event_btn_rechercherActionPerformed

    private void txt_rechercherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rechercherKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rechercherKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionClients.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionClients.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionClients.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionClients.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionClients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_afficher;
    private javax.swing.JButton btn_ajouter;
    private javax.swing.JButton btn_annuler;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_rechercher;
    private javax.swing.JButton btn_retour_dashboard;
    private javax.swing.JButton btn_supprimer;
    private javax.swing.JComboBox<String> cb_ville;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_clients;
    private javax.swing.JTextField txt_adresse;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fonction;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_prenom;
    private javax.swing.JTextField txt_rechercher;
    private javax.swing.JTextField txt_telephone;
    // End of variables declaration//GEN-END:variables
}
